<Project>
  <Import Project="..\..\Directory.Build.props"/>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <WarningsAsErrors>nullable;</WarningsAsErrors>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup>
    <PolySharpExcludeGeneratedTypes>
      System.Runtime.CompilerServices.ModuleInitializerAttribute;
    </PolySharpExcludeGeneratedTypes>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Phymnary.SugarPot.RoslynComponents" />
    <PackageReference Include="SourceGenerator.Foundations" />
  </ItemGroup>

</Project>